[package]
name = "viewpour"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"

[profile.dev]
opt-level = 1
lto = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
